Add basic form and search parameters
CityOfBoston/dog-licenses pull request #10
Opened 2017-06-26 19:53 UTC by powazek

2017-06-26 21:13 UTC, fionawhim requested changes
Just a few little things. After this PR is in, I'd recommend doing a change from "death" to "dog" for all of the directories and paths, and put that up as a PR of its own. Renames are always best to handle on their own.

2017-06-26 21:13 UTC, finneganh commented on client/death/FormPage.js
> +              <style textAlign="right" />
What are you trying to achieve here? I think you probably want `style={{textAlign: 'right'}}` on the `<input />` below.

2017-06-26 21:13 UTC, finneganh commented on client/death/FormPage.js
> +    //const { query } = this.state;
Just remove query from here and from the state.

2017-06-26 21:13 UTC, finneganh commented on client/death/FormPage.js
>                  id="text"
You’ll need to update these `id`s so that they're unique.

2017-06-26 21:13 UTC, finneganh commented on client/death/FormPage.js
> +  handleQueryChange = (ev: SyntheticInputEvent) => {
can remove this method.

2017-06-27 15:03 UTC, powazek commented on client/death/FormPage.js
> +              <style textAlign="right" />
I was just testing with this to see if it changed position, I'll remove it

2017-06-27 15:03 UTC, powazek commented on client/death/FormPage.js
> +    //const { query } = this.state;
Done!

2017-06-27 15:04 UTC, powazek commented on client/death/FormPage.js
> +  handleQueryChange = (ev: SyntheticInputEvent) => {
Done

2017-06-27 16:13 UTC, fionawhim requested changes

2017-06-27 16:13 UTC, finneganh commented on client/death/FormPage.js
> +                id="lookup-firstname"
Be consistent w/ casing. `firstName`

2017-06-27 16:13 UTC, finneganh commented on client/death/FormPage.js
>                <label htmlFor="text" className="txt-l">Owner First Name</label>
`htmlFor` attributes need to match the `id`s of the `input` elements, here and below.

2017-06-27 16:13 UTC, finneganh commented on client/death/FormPage.js
> +              <style textAlign="right" />
Remember to remove.

2017-06-27 16:13 UTC, finneganh commented on client/death/FormPage.js
> +                <select name="breed" id="lookup-breed" className="sel-f">
Should have `value={this.state.breed}`

2017-06-27 16:13 UTC, finneganh commented on client/death/FormPage.js
> +                <select name="color" id="lookup-color" className="sel-f">
`value` attribute here, too

2017-06-27 16:13 UTC, finneganh commented on client/death/FormPage.js
> +                <select name="sex" id="lookup-sex" className="sel-f">
`value`

2017-06-27 17:54 UTC, finneganh commented on client/death/FormPage.js
>                  id="lookup-firstname"
Need to update this ID to match case.

2017-06-27 17:55 UTC, fionawhim approved these changes
Fix these two tiny, things, then you're OK to merge this.

2017-06-27 17:55 UTC, finneganh commented on client/death/FormPage.js
> +              <style textAlign="right" />
Still there?

2017-06-27 17:55 UTC, finneganh commented
If tests pass, that is.

2017-06-27 17:56 UTC, powazek commented on client/death/FormPage.js
>                  id="lookup-firstname"
Done! What is the second tiny thing?

2017-06-27 20:41 UTC, merged